name: First workflow

on:
  push: 
    branches: 
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print welcome message
        run: echo "welcome to acction"

      - name: checkout repo
        uses: actions/checkout@4.2.2

      - name: list reop files
        run: ls -la
       
        
